name: webant_internship
description: Тестовое задание для стажировки WEBANT

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.5
  sizer: ^2.0.15
  go_router: ^7.1.1
  json_annotation: ^4.8.1
  dio: ^5.2.1+1
  image_picker: ^0.8.7+5
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  intl: ^0.18.1



  data:
    path: ./data
  domain:
    path: ./domain
  get_it: ^7.6.0
  flutter_secure_storage: ^8.0.0
  flutter_localization: ^0.1.12
  camera: ^0.10.5+2
  image_picker_plus: ^0.5.6+2
  path_provider: ^2.0.15
  permission_handler: ^10.3.0
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.1

dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.6.2
  build_runner: ^2.3.3

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true